# Generated by Django 4.1.7 on 2024-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("court_detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketballgame",
            name="corners",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="basketballgame",
            name="distortion_parameters",
            field=models.JSONField(default=dict),
        ),
    ]
